### ISSUE TITLE
Add Dynamic Tag Support

### ISSUE THREAD

**Issue by dhershman1** [ConnorWiseman/koa-hbs-renderer#3]
So currently if a lyout does not use `{{{body}}}` for its views then they will not render, I suggest adding dynamic support for this into options. 

I already made a change to the code but I can't open a PR because I don't want to add this as a part of my current PR (since its such a huge difference)

To address this I did the following:

```js
let opts = Object.assign({
    defaultLayout: 'default',
    expires:       60,
    extension:     '.hbs',
    contentTag: 'body' // <--- added the option to our defaults so it just defaults to body if not set
  }, options);
```
And then just change the renderView function to create a property for that tag in context, and set it to our template. 
```js
function renderView(view, layout, context, options) {
    context[opts.contentTag] = view(context, options);

    return layout(context, options);
  };
```

Annnd done we now support dynamic contentTags if they don't want to use body.

**Comment by ConnorWiseman** [comment]
The only reason I went with `{{{body}}}` was because that was the convention from the old Express apps ([express-handlebars](https://github.com/ericf/express-handlebars#basic-usage) & [express-hbs](https://github.com/barc/express-hbs#syntax)), and because I've seen similar helper names used in a few other Node projects ([Ghost](https://themes.ghost.org/docs/handlebars#section-layout-expressions) for starters). Figured it'd be more familiar to folks used to layout stuff.

As you've just demonstrated it's easy enough to implement, but I'm curious-- what's your use case here?

**Comment by dhershman1** [comment]
Flexibility really, I've always used content, or the like I've never actually used body as my main tag lol.

**Comment by ConnorWiseman** [comment]
This got added in 1.0.0. In fact, the default got switched to `{{{content}}}`, because why not?
